USE college;

CREATE TABLE DEPARTMENT(
DepartmentId INT PRIMARY KEY,
DepartmentName VARCHAR(20)
);

CREATE TABLE WORKERS(
WorkerId INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Email VARCHAR(50) UNIQUE,
DepartmentID INT,
FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentId)
);